arb-dir: lib/l10n/arb
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: l10n.dart
synthetic-package: false
nullable-getter: false
#untranslated-messages-file: poruke.dart
