name: common
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  equatable: ^2.0.5 
  injectable: ^2.3.0
  domain_models:
    path: ../domain_models
  
dev_dependencies:
  lints: ^2.0.0
  injectable_generator: 
  build_runner: 