name: repository
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  injectable: ^2.3.0
  import_sorter: ^4.6.0
  emotion_station_api:
    path: ../emotion_station_api
  domain_models:
    path: ../domain_models
  common:
    path: ../common
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  lints: ^2.0.0
  injectable_generator:
  build_runner:
